# baseURL = "https://zhangluther.github.io/blog_zwtech"
relativeURLs = true
baseURL = "/"
title = "ZW技术分享"
author = "ZW"
copyright = "ZW"
pagination.pagerSize = 10
languageCode = "cn"
theme = "tailwind"

[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "logo.webp"
    title = "技术.AI.设计"

  [params.footer]
    since = 2025
    poweredby = false

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
